import { PrismaClient } from "@prisma/client";

export async function seedVariants(prisma: PrismaClient) {
  const variants = [
    {
      id: "var-grn-500g",
      productId: "prod-grn-energetico",
      name: "Paquete 500g",
      costPrice: 8500.00,
      salePrice: 14990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-1kg",
      productId: "prod-grn-energetico",
      name: "Paquete 1kg",
      costPrice: 15000.00,
      salePrice: 25990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-5kg",
      productId: "prod-grn-energetico",
      name: "Saco 5kg",
      costPrice: 60000.00,
      salePrice: 99990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-10kg",
      productId: "prod-grn-energetico",
      name: "Saco 10kg",
      costPrice: 110000.00,
      salePrice: 189990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-250g",
      productId: "prod-conc-proteico",
      name: "Envase 250g",
      costPrice: 12000.00,
      salePrice: 19500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-500g",
      productId: "prod-conc-proteico",
      name: "Envase 500g",
      costPrice: 22000.00,
      salePrice: 35000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-1kg",
      productId: "prod-conc-proteico",
      name: "Envase 1kg",
      costPrice: 40000.00,
      salePrice: 65000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-barras-10p",
      productId: "prod-barras-impulso",
      name: "Pack de 10 unidades",
      costPrice: 7000.00,
      salePrice: 11990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-barras-20p",
      productId: "prod-barras-impulso",
      name: "Pack de 20 unidades",
      costPrice: 12000.00,
      salePrice: 19990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-form-1kg",
      productId: "prod-formula-crecimiento",
      name: "Envase 1kg",
      costPrice: 20000.00,
      salePrice: 34000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-form-2kg",
      productId: "prod-formula-crecimiento",
      name: "Envase 2kg",
      costPrice: 35000.00,
      salePrice: 59000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-hidr-500ml",
      productId: "prod-hidratacion-plasma",
      name: "Botella 500ml",
      costPrice: 4000.00,
      salePrice: 7500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-hidr-1l",
      productId: "prod-hidratacion-plasma",
      name: "Botella 1 Litro",
      costPrice: 7000.00,
      salePrice: 12990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-alim-terap-500g",
      productId: "prod-alimento-medicado",
      name: "Envase 500g",
      costPrice: 25000.00,
      salePrice: 42000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-alim-terap-1_5kg",
      productId: "prod-alimento-medicado",
      name: "Envase 1.5kg",
      costPrice: 60000.00,
      salePrice: 99000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-shamp-250ml",
      productId: "prod-shampoo-bioregen",
      name: "Envase 250ml",
      costPrice: 6000.00,
      salePrice: 10500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-shamp-500ml",
      productId: "prod-shampoo-bioregen",
      name: "Envase 500ml",
      costPrice: 10000.00,
      salePrice: 17500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-acond-250ml",
      productId: "prod-acond-ultrabrillo",
      name: "Envase 250ml",
      costPrice: 5500.00,
      salePrice: 9990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-acond-500ml",
      productId: "prod-acond-ultrabrillo",
      name: "Envase 500ml",
      costPrice: 9000.00,
      salePrice: 15990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-spray-200ml",
      productId: "prod-spray-desinfec",
      name: "Atomizador 200ml",
      costPrice: 3500.00,
      salePrice: 6990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-spray-500ml",
      productId: "prod-spray-desinfec",
      name: "Atomizador 500ml",
      costPrice: 7000.00,
      salePrice: 12990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-toallas-20p",
      productId: "prod-toallas-hipoaler",
      name: "Paquete de 20 unidades",
      costPrice: 4000.00,
      salePrice: 7000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-toallas-50p",
      productId: "prod-toallas-hipoaler",
      name: "Paquete de 50 unidades",
      costPrice: 8000.00,
      salePrice: 13500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-perfume-100ml",
      productId: "prod-perfume-quantum",
      name: "Frasco 100ml",
      costPrice: 10000.00,
      salePrice: 18000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-perfume-recarga",
      productId: "prod-perfume-quantum",
      name: "Recarga 200ml",
      costPrice: 15000.00,
      salePrice: 28000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-supl-100g",
      productId: "prod-suplemento-macro",
      name: "Envase 100g",
      costPrice: 15000.00,
      salePrice: 24990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-supl-500g",
      productId: "prod-suplemento-macro",
      name: "Envase 500g",
      costPrice: 60000.00,
      salePrice: 95000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-analiz-std",
      productId: "prod-analizador-bio",
      name: "Versión Estándar",
      costPrice: 80000.00,
      salePrice: 149990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-analiz-pro",
      productId: "prod-analizador-bio",
      name: "Versión Pro",
      costPrice: 150000.00,
      salePrice: 279990.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-bandas-m",
      productId: "prod-bandas-recuperacion",
      name: "Talla M (Set 2)",
      costPrice: 12000.00,
      salePrice: 22000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-bandas-l",
      productId: "prod-bandas-recuperacion",
      name: "Talla L (Set 2)",
      costPrice: 15000.00,
      salePrice: 27000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-gel-50g",
      productId: "prod-gel-cicatrizante",
      name: "Tubo 50g",
      costPrice: 7000.00,
      salePrice: 12500.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-gel-100g",
      productId: "prod-gel-cicatrizante",
      name: "Tubo 100g",
      costPrice: 12000.00,
      salePrice: 20000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-s",
      productId: "prod-arnes-tactico",
      name: "Talla S",
      costPrice: 25000.00,
      salePrice: 45000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-m",
      productId: "prod-arnes-tactico",
      name: "Talla M",
      costPrice: 30000.00,
      salePrice: 55000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-l",
      productId: "prod-arnes-tactico",
      name: "Talla L",
      costPrice: 35000.00,
      salePrice: 65000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-correa-1_5m",
      productId: "prod-correa-fibra",
      name: "1.5m Estándar",
      costPrice: 18000.00,
      salePrice: 32000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-correa-3m",
      productId: "prod-correa-fibra",
      name: "3m Extensible",
      costPrice: 25000.00,
      salePrice: 45000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-collar-luz-m",
      productId: "prod-collar-luminico",
      name: "Talla M",
      costPrice: 15000.00,
      salePrice: 28000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-collar-luz-l",
      productId: "prod-collar-luminico",
      name: "Talla L",
      costPrice: 18000.00,
      salePrice: 32000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-placas-acero",
      productId: "prod-placas-identidad",
      name: "Acero Básico",
      costPrice: 5000.00,
      salePrice: 9000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-placas-titanio",
      productId: "prod-placas-identidad",
      name: "Titanio Reforzado",
      costPrice: 9000.00,
      salePrice: 16000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-comedero-basico",
      productId: "prod-comedero-inteligente",
      name: "Modelo Básico",
      costPrice: 40000.00,
      salePrice: 75000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-comedero-avanzado",
      productId: "prod-comedero-inteligente",
      name: "Modelo Avanzado",
      costPrice: 70000.00,
      salePrice: 129000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-manta-std",
      productId: "prod-manta-termica",
      name: "Estándar",
      costPrice: 20000.00,
      salePrice: 38000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-manta-reforzada",
      productId: "prod-manta-termica",
      name: "Reforzada",
      costPrice: 30000.00,
      salePrice: 55000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-simulador-lite",
      productId: "prod-simulador-vortex",
      name: "Versión Lite",
      costPrice: 90000.00,
      salePrice: 160000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-simulador-pro",
      productId: "prod-simulador-vortex",
      name: "Versión Profesional",
      costPrice: 180000.00,
      salePrice: 320000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-disp-compacto",
      productId: "prod-dispensador-refuerzo",
      name: "Modelo Compacto",
      costPrice: 30000.00,
      salePrice: 55000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-disp-premium",
      productId: "prod-dispensador-refuerzo",
      name: "Modelo Premium",
      costPrice: 50000.00,
      salePrice: 89000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-guia-anual",
      productId: "prod-guia-cognitiva",
      name: "Licencia Anual",
      costPrice: 20000.00,
      salePrice: 35000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-guia-perpetua",
      productId: "prod-guia-cognitiva",
      name: "Licencia Perpetua",
      costPrice: 50000.00,
      salePrice: 80000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-pista-basica",
      productId: "prod-pista-agilidad",
      name: "Módulo Básico",
      costPrice: 70000.00,
      salePrice: 120000.00,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-pista-expansion",
      productId: "prod-pista-agilidad",
      name: "Módulo Expansión",
      costPrice: 40000.00,
      salePrice: 70000.00,
      stock: 0,
      imageUrl: null,
    },
  ];

  for (const v of variants) {
    await prisma.productVariant.upsert({
      where: { id: v.id },
      update: {
        productId: v.productId,
        name: v.name,
        costPrice: v.costPrice,
        salePrice: v.salePrice,
        stock: v.stock,
        imageUrl: v.imageUrl,
      },
      create: v,
    });
  }

  console.log(`${variants.length} variantes agregadas`);
}
