import { PrismaClient } from "@prisma/client";

export async function seedVariants(prisma: PrismaClient) {
  const variants = [
    {
      id: "var-grn-500g",
      productId: "prod-grn-energetico",
      name: "Paquete 500g",
      costPrice: 8.5,
      salePrice: 14.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-1kg",
      productId: "prod-grn-energetico",
      name: "Paquete 1kg",
      costPrice: 15.0,
      salePrice: 25.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-5kg",
      productId: "prod-grn-energetico",
      name: "Saco 5kg",
      costPrice: 60.0,
      salePrice: 99.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-grn-10kg",
      productId: "prod-grn-energetico",
      name: "Saco 10kg",
      costPrice: 110.0,
      salePrice: 189.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-250g",
      productId: "prod-conc-proteico",
      name: "Envase 250g",
      costPrice: 12.0,
      salePrice: 19.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-500g",
      productId: "prod-conc-proteico",
      name: "Envase 500g",
      costPrice: 22.0,
      salePrice: 35.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-conc-1kg",
      productId: "prod-conc-proteico",
      name: "Envase 1kg",
      costPrice: 40.0,
      salePrice: 65.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-barras-10p",
      productId: "prod-barras-impulso",
      name: "Pack de 10 unidades",
      costPrice: 7.0,
      salePrice: 11.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-barras-20p",
      productId: "prod-barras-impulso",
      name: "Pack de 20 unidades",
      costPrice: 12.0,
      salePrice: 19.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-form-1kg",
      productId: "prod-formula-crecimiento",
      name: "Envase 1kg",
      costPrice: 20.0,
      salePrice: 34.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-form-2kg",
      productId: "prod-formula-crecimiento",
      name: "Envase 2kg",
      costPrice: 35.0,
      salePrice: 59.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-hidr-500ml",
      productId: "prod-hidratacion-plasma",
      name: "Botella 500ml",
      costPrice: 4.0,
      salePrice: 7.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-hidr-1l",
      productId: "prod-hidratacion-plasma",
      name: "Botella 1 Litro",
      costPrice: 7.0,
      salePrice: 12.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-alim-terap-500g",
      productId: "prod-alimento-medicado",
      name: "Envase 500g",
      costPrice: 25.0,
      salePrice: 42.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-alim-terap-1_5kg",
      productId: "prod-alimento-medicado",
      name: "Envase 1.5kg",
      costPrice: 60.0,
      salePrice: 99.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-shamp-250ml",
      productId: "prod-shampoo-bioregen",
      name: "Envase 250ml",
      costPrice: 6.0,
      salePrice: 10.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-shamp-500ml",
      productId: "prod-shampoo-bioregen",
      name: "Envase 500ml",
      costPrice: 10.0,
      salePrice: 17.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-acond-250ml",
      productId: "prod-acond-ultrabrillo",
      name: "Envase 250ml",
      costPrice: 5.5,
      salePrice: 9.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-acond-500ml",
      productId: "prod-acond-ultrabrillo",
      name: "Envase 500ml",
      costPrice: 9.0,
      salePrice: 15.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-spray-200ml",
      productId: "prod-spray-desinfec",
      name: "Atomizador 200ml",
      costPrice: 3.5,
      salePrice: 6.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-spray-500ml",
      productId: "prod-spray-desinfec",
      name: "Atomizador 500ml",
      costPrice: 7.0,
      salePrice: 12.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-toallas-20p",
      productId: "prod-toallas-hipoaler",
      name: "Paquete de 20 unidades",
      costPrice: 4.0,
      salePrice: 7.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-toallas-50p",
      productId: "prod-toallas-hipoaler",
      name: "Paquete de 50 unidades",
      costPrice: 8.0,
      salePrice: 13.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-perfume-100ml",
      productId: "prod-perfume-quantum",
      name: "Frasco 100ml",
      costPrice: 10.0,
      salePrice: 18.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-perfume-recarga",
      productId: "prod-perfume-quantum",
      name: "Recarga 200ml",
      costPrice: 15.0,
      salePrice: 28.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-supl-100g",
      productId: "prod-suplemento-macro",
      name: "Envase 100g",
      costPrice: 15.0,
      salePrice: 24.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-supl-500g",
      productId: "prod-suplemento-macro",
      name: "Envase 500g",
      costPrice: 60.0,
      salePrice: 95.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-analiz-std",
      productId: "prod-analizador-bio",
      name: "Versión Estándar",
      costPrice: 80.0,
      salePrice: 149.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-analiz-pro",
      productId: "prod-analizador-bio",
      name: "Versión Pro",
      costPrice: 150.0,
      salePrice: 279.99,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-bandas-m",
      productId: "prod-bandas-recuperacion",
      name: "Talla M (Set 2)",
      costPrice: 12.0,
      salePrice: 22.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-bandas-l",
      productId: "prod-bandas-recuperacion",
      name: "Talla L (Set 2)",
      costPrice: 15.0,
      salePrice: 27.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-gel-50g",
      productId: "prod-gel-cicatrizante",
      name: "Tubo 50g",
      costPrice: 7.0,
      salePrice: 12.5,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-gel-100g",
      productId: "prod-gel-cicatrizante",
      name: "Tubo 100g",
      costPrice: 12.0,
      salePrice: 20.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-s",
      productId: "prod-arnes-tactico",
      name: "Talla S",
      costPrice: 25.0,
      salePrice: 45.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-m",
      productId: "prod-arnes-tactico",
      name: "Talla M",
      costPrice: 30.0,
      salePrice: 55.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-arnes-l",
      productId: "prod-arnes-tactico",
      name: "Talla L",
      costPrice: 35.0,
      salePrice: 65.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-correa-1_5m",
      productId: "prod-correa-fibra",
      name: "1.5m Estándar",
      costPrice: 18.0,
      salePrice: 32.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-correa-3m",
      productId: "prod-correa-fibra",
      name: "3m Extensible",
      costPrice: 25.0,
      salePrice: 45.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-collar-luz-m",
      productId: "prod-collar-luminico",
      name: "Talla M",
      costPrice: 15.0,
      salePrice: 28.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-collar-luz-l",
      productId: "prod-collar-luminico",
      name: "Talla L",
      costPrice: 18.0,
      salePrice: 32.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-placas-acero",
      productId: "prod-placas-identidad",
      name: "Acero Básico",
      costPrice: 5.0,
      salePrice: 9.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-placas-titanio",
      productId: "prod-placas-identidad",
      name: "Titanio Reforzado",
      costPrice: 9.0,
      salePrice: 16.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-comedero-basico",
      productId: "prod-comedero-inteligente",
      name: "Modelo Básico",
      costPrice: 40.0,
      salePrice: 75.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-comedero-avanzado",
      productId: "prod-comedero-inteligente",
      name: "Modelo Avanzado",
      costPrice: 70.0,
      salePrice: 129.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-manta-std",
      productId: "prod-manta-termica",
      name: "Estándar",
      costPrice: 20.0,
      salePrice: 38.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-manta-reforzada",
      productId: "prod-manta-termica",
      name: "Reforzada",
      costPrice: 30.0,
      salePrice: 55.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-simulador-lite",
      productId: "prod-simulador-vortex",
      name: "Versión Lite",
      costPrice: 90.0,
      salePrice: 160.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-simulador-pro",
      productId: "prod-simulador-vortex",
      name: "Versión Profesional",
      costPrice: 180.0,
      salePrice: 320.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-disp-compacto",
      productId: "prod-dispensador-refuerzo",
      name: "Modelo Compacto",
      costPrice: 30.0,
      salePrice: 55.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-disp-premium",
      productId: "prod-dispensador-refuerzo",
      name: "Modelo Premium",
      costPrice: 50.0,
      salePrice: 89.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-guia-anual",
      productId: "prod-guia-cognitiva",
      name: "Licencia Anual",
      costPrice: 20.0,
      salePrice: 35.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-guia-perpetua",
      productId: "prod-guia-cognitiva",
      name: "Licencia Perpetua",
      costPrice: 50.0,
      salePrice: 80.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-pista-basica",
      productId: "prod-pista-agilidad",
      name: "Módulo Básico",
      costPrice: 70.0,
      salePrice: 120.0,
      stock: 0,
      imageUrl: null,
    },
    {
      id: "var-pista-expansion",
      productId: "prod-pista-agilidad",
      name: "Módulo Expansión",
      costPrice: 40.0,
      salePrice: 70.0,
      stock: 0,
      imageUrl: null,
    },
  ];

  for (const v of variants) {
    await prisma.productVariant.upsert({
      where: { id: v.id },
      update: {
        productId: v.productId,
        name: v.name,
        costPrice: v.costPrice,
        salePrice: v.salePrice,
        stock: v.stock,
        imageUrl: v.imageUrl,
      },
      create: v,
    });
  }

  console.log(`${variants.length} variantes agregadas`);
}
