import { PrismaClient } from "@prisma/client";

export async function seedCustomers(prisma: PrismaClient) {
  const customers = [
    {
      id: "cust-ent-gamma",
      name: "Entidad Gamma-7",
      phone: "+34 600 000 007",
      email: "gamma7@abysstracker.local",
      address: "Sector Primario 101, Zona Cero, Nexus Principal",
      isActive: true,
      createdAt: new Date("2025-01-05T09:00:00Z"),
    },
    {
      id: "cust-consorcio-delta",
      name: "Consorcio Delta-9",
      phone: "+34 600 000 009",
      email: "delta9@abysstracker.local",
      address: "Avenida Estelar 23, Distrito de Datos, Nexo Urbano",
      isActive: true,
      createdAt: new Date("2025-01-15T10:00:00Z"),
    },
    {
      id: "cust-agente-sombra",
      name: "Agente Sombra 12",
      phone: "+34 600 000 012",
      email: "sombra12@abysstracker.local",
      address: "Ruta Oculta 5, Sector Crepuscular, Distrito Beta",
      isActive: true,
      createdAt: new Date("2025-02-01T11:00:00Z"),
    },
    {
      id: "cust-operador-echo",
      name: "Operador Clave Echo",
      phone: "+34 600 000 015",
      email: "echo@abysstracker.local",
      address: "Terminal Sigma 77, Estación Alpha, Perímetro Exterior",
      isActive: true,
      createdAt: new Date("2025-02-10T12:00:00Z"),
    },
    {
      id: "cust-protocolo-zenit",
      name: "Protocolo Zenit",
      phone: "+34 600 000 021",
      email: "zenit@abysstracker.local",
      address: "Bloque 4 Nivel 8, Matriz Principal, Centro de Comando",
      isActive: true,
      createdAt: new Date("2025-03-01T13:00:00Z"),
    },
    {
      id: "cust-observador-03",
      name: "Observador Unitario 03",
      phone: "+34 600 000 024",
      email: "obs03@abysstracker.local",
      address: "Puesto de Avanzada 1, Frontera Exterior, Zona Vigilada",
      isActive: true,
      createdAt: new Date("2025-03-15T14:00:00Z"),
    },
    {
      id: "cust-red-spectral",
      name: "Red Spectral Ltda.",
      phone: "+34 600 000 030",
      email: "contacto@redspectral.local",
      address: "Centro Logístico A-5, Distrito Industrial, Zona de Descarga",
      isActive: true,
      createdAt: new Date("2025-04-01T15:00:00Z"),
    },
    {
      id: "cust-vanguardia-alpha",
      name: "Vanguardia Alpha",
      phone: "+34 600 000 033",
      email: "alpha@abysstracker.local",
      address: "Base Oculta Kappa, Región 3, Área Clasificada",
      isActive: true,
      createdAt: new Date("2025-04-10T16:00:00Z"),
    },
    {
      id: "cust-enlace-omicron",
      name: "Enlace Omikron",
      phone: "+34 600 000 036",
      email: "omikron@abysstracker.local",
      address: "Sub-Nivel 12, Ciudad Subterránea, Sector Profundo",
      isActive: true,
      createdAt: new Date("2025-05-01T09:00:00Z"),
    },
    {
      id: "cust-unidad-nova",
      name: "Unidad Nova-Prime",
      phone: "+34 600 000 040",
      email: "nova.prime@abysstracker.local",
      address: "Torre Zenith 3, Sector Alta Gama, Zona Residencial",
      isActive: true,
      createdAt: new Date("2025-05-10T10:00:00Z"),
    },
    {
      id: "cust-centinela-echo",
      name: "Centinela Echo-8",
      phone: "+34 600 000 041",
      email: "echo8@abysstracker.local",
      address: "Puesto de Vigilancia 2, Perímetro Norte, Zona de Alerta",
      isActive: true,
      createdAt: new Date("2025-06-01T11:00:00Z"),
    },
    {
      id: "cust-explorador-zeta",
      name: "Explorador Zeta-Beta",
      phone: "+34 600 000 042",
      email: "zetabeta@abysstracker.local",
      address: "Zona Inexplorada, Cuadrante Delta, Área de Reconocimiento",
      isActive: true,
      createdAt: new Date("2025-06-10T12:00:00Z"),
    },
    {
      id: "cust-arquitecto-nx",
      name: "Arquitecto NX-7",
      phone: "+34 600 000 043",
      email: "nx7@abysstracker.local",
      address: "Cámara de Diseño 9, Complejo Central, Laboratorio Alfa",
      isActive: true,
      createdAt: new Date("2025-07-01T13:00:00Z"),
    },
    {
      id: "cust-guardian-temporal",
      name: "Guardián Temporal",
      phone: "+34 600 000 044",
      email: "guardian.temp@abysstracker.local",
      address: "Depósito de Datos Históricos, Archivo R-9, Sector de Respaldo",
      isActive: true,
      createdAt: new Date("2025-07-10T14:00:00Z"),
    },
    {
      id: "cust-entidad-inactiva",
      name: "Entidad Inactiva Prueba",
      phone: "+34 600 000 099",
      email: "inactiva@abysstracker.local",
      address: "Sector Obsoleto, Archivo Muerto, Zona de Desuso",
      isActive: false,
      createdAt: new Date("2025-08-01T15:00:00Z"),
    },
  ];

  for (const c of customers) {
    await prisma.customer.upsert({
      where: { id: c.id },
      update: {
        name: c.name,
        phone: c.phone,
        email: c.email,
        address: c.address,
        isActive: c.isActive,
        createdAt: c.createdAt,
      },
      create: c,
    });
  }

  console.log(`${customers.length} clientes agregados`);
}
