"use client";

import { cn } from "@/lib/utils";
import {
  LucideProps,
  Loader2,
  AlertCircle,
  CheckCircle2,
  XCircle,
  X,
  Sun,
  Moon,
  ChevronDown,
  Search,
  Download,
  Info,
  LayoutDashboard,
  ShoppingBag,
  Calendar,
  Receipt,
  Package,
  Scale,
  Users,
  PawPrint,
  UserCircle,
  DollarSign,
  LineChart,
  Shield,
  LogOut,
  Menu,
  ChevronRight,
  ChevronLeft,
  Banknote,
  Landmark,
  Book,
  User,
  Plus,
  Trash2,
  Scissors,
  ArrowRight,
  PackageOpen,
  ImageOff,
  ShoppingCart,
  Sparkles,
  ArrowDownCircle,
  PackageMinus,
  AlertTriangle,
  Hand,
  Mail,
  Phone,
  Eye,
  EyeOff,
  Coffee,
  Pencil,
  FileUp,
  Rocket,
  Camera,
  Undo2,
  FileText,
  LayoutGrid,
  Filter,
  List,
  History,
  KeyRound,
  ArrowLeft as LucideArrowLeft,
} from "lucide-react";

export const iconMap = {
  loader: Loader2,
  alert: AlertCircle,
  check: CheckCircle2,
  error: XCircle,
  close: X,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  search: Search,
  download: Download,
  info: Info,
  dashboard: LayoutDashboard,
  pos: ShoppingBag,
  calendar: Calendar,
  sales: Receipt,
  stock: Package,
  package: Package,
  scale: Scale,
  customers: Users,
  pets: PawPrint,
  owners: UserCircle,
  finance: DollarSign,
  reports: LineChart,
  team: Shield,
  logout: LogOut,
  menu: Menu,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  cash: Banknote,
  bank: Landmark,
  notebook: Book,
  user: User,
  plus: Plus,
  trash: Trash2,
  scissors: Scissors,
  arrowRight: ArrowRight,
  arrowLeft: LucideArrowLeft,
  empty: PackageOpen,
  noImage: ImageOff,
  cart: ShoppingCart,
  sparkles: Sparkles,
  entry: ArrowDownCircle,
  withdrawal: PackageMinus,
  adjustment: AlertTriangle,
  hand: Hand,
  mail: Mail,
  phone: Phone,
  eye: Eye,
  eyeOff: EyeOff,
  coffee: Coffee,
  edit: Pencil,
  upload: FileUp,
  rocket: Rocket,
  camera: Camera,
  adjustmentReturn: Undo2,
  receipt: FileText,
  layout: LayoutGrid,
  filter: Filter,
  list: List,
  history: History,
  key: KeyRound,
};

export type IconName = keyof typeof iconMap;

interface IconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
}

export function Icon({ name, className, ...props }: IconProps) {
  const LucideIcon = iconMap[name];

  if (!LucideIcon) {
    console.warn(`[Icon] El icono "${name}" no está registrado en iconMap.`);
    return null;
  }

  return <LucideIcon className={cn("h-4 w-4", className)} {...props} />;
}
